from .privacy_policy import PRIVACY_POLICY_TEXT, PRIVACY_POLICY_VERSION

APP_NAME = "有迹"
APP_VERSION = "0.1.0"

TIME_FORMAT = "%Y-%m-%d %H:%M:%S"

HISTORY_PERSIST_THRESHOLD_SECONDS = 0
PROJECT_OWNERSHIP_CONFIRM_SECONDS = 0
DEFAULT_IDLE_THRESHOLD_SECONDS = 5 * 60
DEFAULT_CONTEXT_CARRY_MINUTES = 15
REPORT_CONTEXT_SHORT_MERGE_SECONDS = DEFAULT_CONTEXT_CARRY_MINUTES * 60
DEFAULT_UNRECORDED_GAP_BOUNDARY_SECONDS = DEFAULT_CONTEXT_CARRY_MINUTES * 60
RULE_CACHE_TTL_SECONDS = 5.0
CLIPBOARD_RETENTION_DAYS = 30
CLIPBOARD_TRANSITION_SECONDS = 10

STATUS_NORMAL = "normal"
STATUS_IDLE = "idle"
STATUS_PAUSED = "paused"
STATUS_EXCLUDED = "excluded"
STATUS_ERROR = "error"

SOURCE_AUTO = "auto"
SOURCE_MANUAL = "manual"
SOURCE_SYSTEM = "system"

EXCLUDED_APP_NAME = "已排除"
EXCLUDED_PROCESS_NAME = "excluded"
EXCLUDED_WINDOW_TITLE = "已排除窗口"
UNCATEGORIZED_PROJECT = "未归类"
EXCLUDED_PROJECT = "排除规则"

ANCHOR_FILE_EXTENSIONS = (
    ".docx",
    ".doc",
    ".pdf",
    ".xlsx",
    ".xls",
    ".pptx",
    ".ppt",
    ".txt",
    ".md",
    ".csv",
)

# Compatibility aliases used by the existing privacy gate and WebView API.
# The authoritative policy metadata and text live in privacy_policy.py.
PRIVACY_NOTICE_VERSION = PRIVACY_POLICY_VERSION
PRIVACY_NOTICE_TEXT = PRIVACY_POLICY_TEXT
