"""Shared, current-only limits for the FD Work integration boundary."""

FD_WORK_ADAPTER_CONTRACT_VERSION = 4
FD_WORK_CASE_LABEL_MAX_LENGTH = 100
FD_WORK_QUERY_MIN_LENGTH = 0
FD_WORK_QUERY_MAX_LENGTH = FD_WORK_CASE_LABEL_MAX_LENGTH
FD_WORK_SELECTION_TOKEN_MAX_LENGTH = 256
FD_WORK_CASE_SEARCH_LIMIT = 20


__all__ = [
    "FD_WORK_CASE_LABEL_MAX_LENGTH",
    "FD_WORK_ADAPTER_CONTRACT_VERSION",
    "FD_WORK_CASE_SEARCH_LIMIT",
    "FD_WORK_QUERY_MAX_LENGTH",
    "FD_WORK_QUERY_MIN_LENGTH",
    "FD_WORK_SELECTION_TOKEN_MAX_LENGTH",
]
