const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const path=require('node:path'); const vm=require('node:vm');
function harness(){
  const els=new Map(); function el(id){ if(!els.has(id)) els.set(id,{id,value:'',hidden:false,disabled:false,readOnly:false,textContent:'',className:'',attrs:{},listeners:{},getAttribute(k){return this.attrs[k]??null},setAttribute(k,v){this.attrs[k]=String(v)},addEventListener(n,fn,opt){(this.listeners[n]??=[]).push({fn,opt})}}); return els.get(id); }
  ['rules-panel-project-name','rules-panel-fd-work-status','rules-panel-fd-work-picker','rules-panel-fd-work-pick','rules-panel-fd-work-clear'].forEach(el);
  const calls=[]; const baseIdentity={bindHost(){},bindEvents(){},prepareEditor(){},reset(){},syncStatus(){},updateControls(){return{}},buildSavePayload(){return{}},verifyPersistence(){return true}};
  const baseBridge={backfillProjectRule:()=>Promise.resolve({ok:true}),openFDWorkCasePicker:(id)=>{calls.push(['open',id]); return Promise.resolve({ok:true,operation_status:'picker_ready'})},clearFDWorkBindingForRules:(id)=>{calls.push(['clear',id]); return Promise.resolve({ok:true,fd_work_binding:{bound:false}})},updateProjectForRules:(...a)=>{calls.push(['update',...a]); return Promise.resolve({ok:true,project:{id:a[0],name:a[1]}})}};
  const App={projectIdentity:baseIdentity,bridge:Object.freeze(baseBridge),fdWork:{},fdWorkStatus:{enabled:true,session_state:'ready',operation:'none'},safeText:(x,d)=>String(x||d||''),fdWorkStatusText:()=>''};
  const document={readyState:'complete',getElementById:el,addEventListener(){}}; const pycalls=[]; const window={WorkTraceApp:App,pywebview:{api:{cancel_fd_work_case_picker:(id)=>{pycalls.push(id);return Promise.resolve({ok:true,accepted:true})}}}};
  const context={window,document,Promise,Error,setTimeout}; vm.createContext(context); vm.runInContext(fs.readFileSync(path.join(__dirname, '../../worktrace/webview_ui/js/rules_rule_actions.js'),'utf8'),context); return {App:context.window.WorkTraceApp,el,calls,pycalls};
}
test('unlink is an editor draft and persists only after project save',async()=>{ const h=harness(); h.App.projectIdentity.prepareEditor({id:7,name:'CASE A',fd_work_bound:true}); h.el('rules-panel-project-name').value='CASE A'; h.App.projectIdentity.clearSelection(); assert.equal(h.calls.some(c=>c[0]==='clear'),false); const payload=h.App.projectIdentity.buildSavePayload('CASE A',true); assert.equal(payload.clearBinding,true); const result=await h.App.bridge.updateProjectForRules(7,'CASE A','d','中文',null); assert.deepEqual(h.calls.map(c=>c[0]),['update','clear']); assert.equal(result.fd_work_binding.bound,false); assert.equal(h.App.projectIdentity.verifyPersistence(result,{name:'CASE A',fd_work_bound:false},result.project),true); });
test('unlink can be toggled back to preserve before save',()=>{ const h=harness(); h.App.projectIdentity.prepareEditor({id:7,name:'CASE A',fd_work_bound:true}); h.el('rules-panel-project-name').value='CASE A'; h.App.projectIdentity.clearSelection(); h.App.projectIdentity.clearSelection(); const payload=h.App.projectIdentity.buildSavePayload('CASE A',true); assert.equal(payload.clearBinding,false); assert.equal(h.App.projectIdentity._testState().saveIntent,'preserve'); });
test('reset detaches a pending picker and requests backend cancellation',async()=>{ const h=harness(); h.App.projectIdentity.prepareEditor(null); h.App.projectIdentity.openPicker(); await Promise.resolve(); const request=h.App.projectIdentity._testState().pickerRequestId; assert.ok(request); h.App.projectIdentity.reset(); await Promise.resolve(); assert.deepEqual(h.pycalls,[request]); assert.equal(h.App.projectIdentity._testState().pickerPending,false); });
test('replacement selection cancels explicit unlink intent',()=>{ const h=harness(); h.App.projectIdentity.prepareEditor({id:7,name:'CASE A',fd_work_bound:true}); h.el('rules-panel-project-name').value='CASE A'; h.App.projectIdentity.clearSelection(); h.App.projectIdentity.openPicker(); const request=h.App.projectIdentity._testState().pickerRequestId; assert.equal(h.App.receiveFDWorkCasePickerResult({ok:true,request_id:request,selected_label:'CASE B',selection_token:'proof'}),true); assert.equal(h.App.projectIdentity._testState().clearBindingOnSave,false); assert.equal(h.el('rules-panel-project-name').value,'CASE B'); });
